export interface IGeneralConfiguration {
  id: number,
  email_alarm: boolean,
  business_days: boolean,
  lunch_duration: string,
  anexo: number,
  letter: number,
  expedient: number,
  external: number,
  internal: number,
  radiable_number: number,
  filed_number_exped: number,
  received: number,
  series: number,
  inventory_record: number,
  inventory_record_detail: number,
  temporary_settlement: boolean,
  standard_temporary_filing: boolean,
}

export interface IGeneralConfigurationTemp {
  id?: number,
  email_alarm: boolean,
  business_days: boolean,
  lunch_duration: string,
  anexo: number,
  letter: number,
  expedient: number,
  external: number,
  internal: number,
  radiable_number: number,
  filed_number_exped: number,
  received: number,
  series: number,
  inventory_record: number,
  inventory_record_detail: number,
  temporary_settlement: boolean,
  standard_temporary_filing: boolean,
}
